/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateForbiddenRouteImport } from './routes/_private/forbidden'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PrivatePlayersRouteRouteImport } from './routes/_private/players/route'
import { Route as PrivatePartnersIndexRouteImport } from './routes/_private/partners/index'
import { Route as PrivateFranchiseGroupsIndexRouteImport } from './routes/_private/franchise-groups/index'
import { Route as PrivateDashboardIndexRouteImport } from './routes/_private/dashboard/index'
import { Route as PrivatePartnersNewRouteImport } from './routes/_private/partners/new'
import { Route as PrivatePartnersPartnerIdRouteImport } from './routes/_private/partners/$partnerId'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateForbiddenRoute = PrivateForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PrivatePlayersRouteRoute = PrivatePlayersRouteRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePartnersIndexRoute = PrivatePartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateFranchiseGroupsIndexRoute =
  PrivateFranchiseGroupsIndexRouteImport.update({
    id: '/franchise-groups/',
    path: '/franchise-groups/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePartnersNewRoute = PrivatePartnersNewRouteImport.update({
  id: '/partners/new',
  path: '/partners/new',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePartnersPartnerIdRoute =
  PrivatePartnersPartnerIdRouteImport.update({
    id: '/partners/$partnerId',
    path: '/partners/$partnerId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players': typeof PrivatePlayersRouteRoute
  '/login': typeof AuthLoginRoute
  '/forbidden': typeof PrivateForbiddenRoute
  '/partners/$partnerId': typeof PrivatePartnersPartnerIdRoute
  '/partners/new': typeof PrivatePartnersNewRoute
  '/dashboard/': typeof PrivateDashboardIndexRoute
  '/franchise-groups/': typeof PrivateFranchiseGroupsIndexRoute
  '/partners/': typeof PrivatePartnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players': typeof PrivatePlayersRouteRoute
  '/login': typeof AuthLoginRoute
  '/forbidden': typeof PrivateForbiddenRoute
  '/partners/$partnerId': typeof PrivatePartnersPartnerIdRoute
  '/partners/new': typeof PrivatePartnersNewRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/franchise-groups': typeof PrivateFranchiseGroupsIndexRoute
  '/partners': typeof PrivatePartnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/players': typeof PrivatePlayersRouteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_private/forbidden': typeof PrivateForbiddenRoute
  '/_private/partners/$partnerId': typeof PrivatePartnersPartnerIdRoute
  '/_private/partners/new': typeof PrivatePartnersNewRoute
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/franchise-groups/': typeof PrivateFranchiseGroupsIndexRoute
  '/_private/partners/': typeof PrivatePartnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/players'
    | '/login'
    | '/forbidden'
    | '/partners/$partnerId'
    | '/partners/new'
    | '/dashboard/'
    | '/franchise-groups/'
    | '/partners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players'
    | '/login'
    | '/forbidden'
    | '/partners/$partnerId'
    | '/partners/new'
    | '/dashboard'
    | '/franchise-groups'
    | '/partners'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/_private/players'
    | '/_auth/login'
    | '/_private/forbidden'
    | '/_private/partners/$partnerId'
    | '/_private/partners/new'
    | '/_private/dashboard/'
    | '/_private/franchise-groups/'
    | '/_private/partners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/forbidden': {
      id: '/_private/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PrivateForbiddenRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_private/players': {
      id: '/_private/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PrivatePlayersRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/partners/': {
      id: '/_private/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PrivatePartnersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/franchise-groups/': {
      id: '/_private/franchise-groups/'
      path: '/franchise-groups'
      fullPath: '/franchise-groups/'
      preLoaderRoute: typeof PrivateFranchiseGroupsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/partners/new': {
      id: '/_private/partners/new'
      path: '/partners/new'
      fullPath: '/partners/new'
      preLoaderRoute: typeof PrivatePartnersNewRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/partners/$partnerId': {
      id: '/_private/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PrivatePartnersPartnerIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivatePlayersRouteRoute: typeof PrivatePlayersRouteRoute
  PrivateForbiddenRoute: typeof PrivateForbiddenRoute
  PrivatePartnersPartnerIdRoute: typeof PrivatePartnersPartnerIdRoute
  PrivatePartnersNewRoute: typeof PrivatePartnersNewRoute
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
  PrivateFranchiseGroupsIndexRoute: typeof PrivateFranchiseGroupsIndexRoute
  PrivatePartnersIndexRoute: typeof PrivatePartnersIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivatePlayersRouteRoute: PrivatePlayersRouteRoute,
  PrivateForbiddenRoute: PrivateForbiddenRoute,
  PrivatePartnersPartnerIdRoute: PrivatePartnersPartnerIdRoute,
  PrivatePartnersNewRoute: PrivatePartnersNewRoute,
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
  PrivateFranchiseGroupsIndexRoute: PrivateFranchiseGroupsIndexRoute,
  PrivatePartnersIndexRoute: PrivatePartnersIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
